### PR TITLE
Columns string generation via bytes.Buffer (statement.genColumnStr)

### PR DESCRIPTION
**Pull request by nemec784**
Rewritten `statement.genColumnStr` for columns string generation via `bytes.Buffer` instead of `strings.Join`

Up to 30% faster, 50% less memory usage and 5 times less allocations per operation (see benchmarks below).

Affects on `session.Find` and `session.Get` on simple queries (i.e. without GroupBy and Join).
<br>

Benchmarks (9 columns):
```
BenchmarkColumnsStringGeneration_Join-4		500000	      2748 ns/op    	 784 B/op	      16 allocs/op
BenchmarkColumnsStringGeneration_Buffer-4      1000000	      1941 ns/op    	 352 B/op	       3 allocs/op
```

### CODE REVIEW

**Comment by lunny** [comment]
Hi, could you run `github.com/go-xorm/tests/sqlite.sh` and `github.com/go-xorm/tests/mysql.sh`. It cannot be passed if I checkout your branch.

**Comment by lunny** [comment]
Thanks!

**Comment by nemec784** [comment]
Hi! Yes, i had missed the case when last column was skipped. I have made changes. Now those tests from `tests` project are successfully pass.

**Comment by nemec784** [comment]
Oh, already merged :-)

**Pull request merged**
