### PR TITLE
Fix BUG: Update statement build function should ingore ONLYFROMDB fields

### PR DESCRIPTION
**Pull request by DrWrong**
the Function `buildUpdates` doesn't ignore ONLYFROMDB fields.

I don't know whether it is a bug or a feature

### CODE REVIEW

**Comment by lunny** [comment]
But CI failed on mysql test

**Comment by DrWrong** [comment]
Modified the testcase 

By the way, I don't think it's a good idea your provide two `GenUpdateColumns` method

```
		if session.statement.ColumnStr == "" {
			colNames, args = session.statement.buildUpdates(bean, false, false,
				false, false, true)
		} else {
			colNames, args, err = session.genUpdateColumns(bean)
			if err != nil {
				return 0, err
			}
		}

```
Maybe should changed it to only one function

**Comment by lunny** [comment]
@DrWrong I agree with you.

**Comment by lunny** [comment]
Thanks!

**Pull request merged**
