### PR TITLE
Newrelic mysql integration

### PR DESCRIPTION
**Pull request by dmitry-nesterenko**

### CODE REVIEW

**Comment by dmitry-nesterenko** [comment]
@lunny 
# cd /go/src/xorm.io/core; git pull --ff-only
fatal: unable to access 'https://gitea.com/xorm/core/': Empty reply from server
package xorm.io/core: exit status 1
Exited with code 1

What can be the cause?
I have no permissions for rebuild

**Comment by lunny** [comment]
I think you can import that as a third-party driver.

**Comment by dmitry-nesterenko** [comment]
@lunny 
But `mysqlDriver` Driver and `mysql` Dialect both are xorm internals

**Comment by lunny** [comment]
You can use `core.QueryDriver` and `core.QueryDialect` to get them and register them use a new name.

**Pull request closed without merging**
