### PR TITLE
mssql: Insert DateTime/Timestamp as UTC time string

### PR DESCRIPTION
**Pull request by linquize**
This makes it consistent with select

### CODE REVIEW

**Comment by lunny** [comment]
Why use UTC() when mssql?

**Comment by linquize** [comment]
Because in session.go: `_row2Bean()`
the value is read as UTC.time
https://github.com/go-xorm/xorm/blob/aa90a634d40e940089ff478bcc18567cdf257a30/session.go#L1708
Then convert to local TZ 
https://github.com/go-xorm/xorm/blob/aa90a634d40e940089ff478bcc18567cdf257a30/session.go#L1716

So we need to make insert and select consistent.

**Comment by tkausl** [comment]
Same problem applies to mysql. datetime is interpreted as UTC when loading from the database and converted to the desired timezone but on write the datetime-string is not converted to UTC.

**Comment by linquize** [comment]
@tkausl If you say the problem also applies to mysql, how to do?

**Comment by tkausl** [comment]
You mean how to fix? add a ```|| engine.dialect.DBType() == core.MYSQL```  to your if-statement

**Pull request closed without merging**
