### PR TITLE
Allow adding prefix for fields with `extends` tag

### PR DESCRIPTION
**Pull request by mskrip**
Added new syntax like `extends('Prefix')` to enable matching all
extended fields as `PrefixFieldName`.

Close go-xorm/xorm#1270

### CODE REVIEW

**Comment by lunny** [comment]
Join Table Alias Name or prefix of the name, which is better?
```
SELECT <extends_name>.width, <extends_name>.height
```
instead of
```
SELECT <extends_name>width, <extends_name>height
```

**Comment by mskrip** [comment]
IMO having just prefix is better here since it refers to what the column name of the query result should be changed to, it doesn't have to have anything in common with the table (the prefix I mean).

**Comment by mskrip** [comment]
Sorry to bother you, but would I be able to get an ETA on this review? This is kind of a blocking change for me.

**Comment by lunny** [comment]
How to handle `SizeClosed *Size `xorm:"extends('')"` ?

**Comment by mskrip** [comment]
Maybe as if there was no argument? So the same as just `xorm:"extends"` ?

**Comment by lunny** [comment]
@mskrip I think it's reasonable.

**Comment by mskrip** [comment]
@lunny Added test for that case

**Comment by mskrip** [comment]
@lunny ping

**Comment by lunny** [comment]
@mskrip will do last review tomorrow morning.

**Comment by mskrip** [comment]
@lunny Okay, thank you

**Comment by lunny** [comment]
@mskrip Thanks!

**Pull request merged**
