### PR TITLE
Make ID also automatic Primary Key

### PR DESCRIPTION
**Pull request by phsmit**
Implementation for #197

### CODE REVIEW

**Comment by lunny** [comment]
For the same reason - compatible, I would like you to custom your xorm tag, For example:
```Go
type MyStruct struct {
    ID int64 `xorm:"'id' pk autoincr"`
}
```

**Comment by phsmit** [comment]
I do think this is less of a compatibility problem. I can't imagine anyone having both Id and ID in their structs. Also, if people have an ID field in their structs I don't think they mean it not to be a primary key.

Having to add the custom xorm tag to every field becomes very cumbersome.

**Comment by phsmit** [comment]
Also, I think xorm should motivate people to write gonic code, so even recommend that people use ID over Id...

**Comment by lunny** [comment]
OK. Let me take a navigation on xorm group on QQ.

**Comment by lunny** [comment]
I have discussed this pr on xorm group on QQ. Most of them think keep compatible is more important even if it will be rarely occupied. And currently it could be resolved used by xorm tag. So I think I will reject this pr. Sorry.

**Pull request closed without merging**
