### PR TITLE
1)add "WhereOnly" function provides custom query condition without bean'...

### PR DESCRIPTION
**Pull request by Michael2008S**
1)add "WhereOnly" function provides custom query condition without bean's non-empty fields for "Get" and "Count"

### CODE REVIEW

**Comment by lunny** [comment]
I prefer to use `NoAutoCondition` to replace the name `WhereOnly`.

**Comment by Michael2008S** [comment]
Use NoAutoCondition to replace the name WhereOnly.

**Comment by lunny** [comment]
I mean `engine.NoAutoCondition().Where("").Get()`. It's more flexible. `NoAutoCondition()` has no any param. And the implementation is more simple.

**Comment by lunny** [comment]
I have implemented this via fad61020e856d1dfe16f44e006d288713feb38fb. So close this issue. Thank you @Michael2008S.

**Pull request closed without merging**
