### PR TITLE
fix issue #1352

### PR DESCRIPTION
**Pull request by guangfnian**

### CODE REVIEW

**Comment by lunny** [comment]
It is unnecessary since `queryRows` will always invoke `resetStatement`.

**Comment by guangfnian** [comment]
> It is unnecessary since `queryRows` will always invoke `resetStatement`.

Have you checked my example in issue #1352 ?

Let's take session.cacheGet() function as an example
```golang
func (session *Session) cacheGet(bean interface{}, sqlStr string, args ...interface{}) (has bool, err error) {
	// skip .........
	table := session.statement.RefTable
	ids, err := core.GetCacheSql(cacher, tableName, newsql, args)
	if err != nil {
		var res = make([]string, len(table.PrimaryKeys))
		rows, err := session.NoCache().queryRows(newsql, args...)
		// skip ........
	} else {
		session.engine.logger.Debug("[cacheGet] cache hit sql:", newsql, ids)
	}
```
The problem is, when cache hit sql, err will be nil, and `queryRows` won't be called !

**Comment by lunny** [comment]
@guangfnian I will send a PR to replace this one and fix that issue.

**Comment by BetaCat0** [comment]
Fixed in #1375

**Pull request closed without merging**
