### PR TITLE
sync2 简单支持自定义表名同步

### PR DESCRIPTION
**Pull request by meiyang1123**

### CODE REVIEW

**Comment by lunny** [comment]
Could you add some test?

**Comment by meiyang1123** [comment]
First ,Use `testEngine.Table(tableName).Sync2(new(TestSync2Index))` to  create a table.
Then, if you change the struct TestSync2Index( such as add a member ) and run `testEngine.Table(tableName).Sync2(new(TestSync2Index))` again. The structure of the table does not change。

**Comment by lunny** [comment]
replaced by #1445

**Comment by lunny** [comment]
replaced by #1445

**Pull request closed without merging**
