### PR TITLE
add support sql.NullString sql.NullInt64 ...

### PR DESCRIPTION
**Pull request by winxxp**
支持sql.NullString、sql.NullInt64等支持sql.Scanner和driver.Valuer接口的结构。

### CODE REVIEW

**Comment by winxxp** [comment]
修正支持sql.NullString字段时，使用Iterater方法时崩溃。

**Comment by lunny** [comment]
Good job. And could you add some tests on github.com/go-xorm/tests. So I can merge this pr. @winxxp

**Comment by winxxp** [comment]
````
--- PASS: TestMysqlWithCacheSameMapper (34.24s)
PASS
ok      github.com/go-xorm/tests/mysql  179.740s
/d/golib/src/github.com/go-xorm/tests
````

**Comment by lunny** [comment]
Could you pull request your tests to github.com/go-xorm/tests?

**Comment by lunny** [comment]
Thanks.

**Pull request merged**
